### ISSUE TITLE
Report data frequency

### ISSUE THREAD

**Issue by ndrest-amzn** [aws-samples/ams-self-service-reporting-aggregator#2]
Hi,
How recent is the data generated and displayed? 
I'd like to view latest backup status data at 9am for backup jobs that run at 4am? Is this supported?

**Comment by jetennan** [comment]
Hello @ndrest-amzn 

This solution aggregates data provided by AMS Self-Service Reporting, it doesn't interrogate backup jobs directly to build reports. Therefore, this solution has a dependency on when AMS releases reports. By default, this solution runs at 21:00 UTC because AMS's daily ETL jobs have typically completed by this time. AMS ETL tasks run on a fixed daily schedule.

Due to the variance between workloads, even within a single AMS customer, there may be no optimal time to create backup reporting. AMS supports customers globally, which introduces further variance and complexity.

Hope this helps
Jeremy
